name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    name: Build and Publish Resume
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2

    - name: Build LaTeX
      uses: xu-cheng/latex-action@v3
      with:
        root_file: resume.tex
        latexmk_use_lualatex: true
        texlive_version: 2020

    - name: Setup Build Folder
      run: |
        rm -rf ./build
        mkdir ./build
        cp ./index.html ./build/
        cp ./resume.pdf ./build/

    - name: Publish Website
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: 'build'
        single-commit: true
